// app/api/telegram/send-cogs-pdf/route.tsx

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { TELEGRAM_CONFIG } from '@/lib/telegramConfig';
import { renderToBuffer, Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';

const EXCHANGE_RATE = 4000;
const formatRiel = (val: number) => `${Math.round(val || 0).toLocaleString()} ៛`;

function parseOwner(owner?: string): 'Mom' | 'Pich' | 'Jing' | 'Both' | 'Others' {
  if (!owner) return 'Others';
  const clean = owner.toLowerCase().trim();
  if (clean.includes('mom')) return 'Mom';
  if (clean.includes('pich')) return 'Pich';
  if (clean.includes('jing')) return 'Jing';
  if (clean.includes('both')) return 'Both';
  return 'Others';
}

// --- 1. DEFINE A4 PDF STYLES ---
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#0f172a' },
  headerContainer: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 2, borderColor: '#15803d', paddingBottom: 15, marginBottom: 20 },
  title: { fontSize: 20, fontWeight: 'bold', color: '#15803d' },
  subtitle: { fontSize: 10, color: '#64748b', marginTop: 4 },
  dateText: { fontSize: 12, fontWeight: 'bold', textAlign: 'right' },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', color: '#1e293b', marginTop: 15, marginBottom: 8, backgroundColor: '#f1f5f9', padding: 6 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#fef9c3', borderBottomWidth: 1, borderColor: '#000000', paddingVertical: 6, paddingHorizontal: 4, fontWeight: 'bold' },
  tableRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderColor: '#cbd5e1', paddingVertical: 6, paddingHorizontal: 4 },
  colInv: { width: '12%', textAlign: 'center' },
  colCustomer: { width: '25%' },
  colRice: { width: '28%' },
  colQty: { width: '10%', textAlign: 'center' },
  colPrice: { width: '12%', textAlign: 'right' },
  colTotal: { width: '13%', textAlign: 'right', fontWeight: 'bold' },
  totalBox: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#fef9c3', borderWidth: 1.5, borderColor: '#000000', padding: 12, marginTop: 25 },
  totalLabel: { fontSize: 14, fontWeight: 'bold' },
  totalValue: { fontSize: 16, fontWeight: 'bold', color: '#b58a3d' },
  footer: { position: 'absolute', bottom: 25, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 0.5, borderColor: '#e2e8f0', paddingTop: 8, fontSize: 8, color: '#94a3b8' }
});

// --- 2. DEFINE THE REACT-PDF LAYOUT COMPONENT ---
const CogsReportDocument = ({ rows, grandTotal, fromDate, toDate, tabLabel }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.headerContainer}>
        <View>
          <Text style={styles.title}>🌾 COGS ACCOUNTING SHEET</Text>
          <Text style={styles.subtitle}>{tabLabel} Breakdown Report</Text>
        </View>
        <View>
          <Text style={styles.dateText}>📅 {fromDate === toDate ? fromDate : `${fromDate} to ${toDate}`}</Text>
          <Text style={{ fontSize: 9, color: '#64748b', textAlign: 'right', marginTop: 3 }}>Phnom Penh, Cambodia</Text>
        </View>
      </View>

      {/* Table Header */}
      <View style={styles.tableHeader}>
        <Text style={styles.colInv}>INV</Text>
        <Text style={styles.colCustomer}>CUSTOMER</Text>
        <Text style={styles.colRice}>RICE TYPE</Text>
        <Text style={styles.colQty}>QTY</Text>
        <Text style={styles.colPrice}>PRICE</Text>
        <Text style={styles.colTotal}>TOTAL (KHR)</Text>
      </View>

      {/* Table Rows */}
      {rows.map((row: any, idx: number) => (
        <View key={idx} style={styles.tableRow} wrap={false}>
          <Text style={styles.colInv}>{row.invoice_id ? String(row.invoice_id).replace(/\D/g, '') : '-'}</Text>
          <Text style={styles.colCustomer}>{row.customer_name || 'Walk-in'}</Text>
          <Text style={styles.colRice}>{row.rice_type || row.custom_rice_type || '-'}</Text>
          <Text style={styles.colQty}>{Number(row.qty || 0).toLocaleString()}</Text>
          <Text style={styles.colPrice}>{Number(row.cogs_price || 0).toLocaleString()}</Text>
          <Text style={[styles.colTotal, row.isNegative ? { color: '#dc2626' } : {}]}>
            {Math.round(row.calculatedAmount || 0).toLocaleString()}
          </Text>
        </View>
      ))}

      {/* Grand Total Box */}
      <View style={styles.totalBox} wrap={false}>
        <Text style={styles.totalLabel}>TOTAL COGS DUE:</Text>
        <Text style={styles.totalValue}>{formatRiel(grandTotal)}</Text>
      </View>

      {/* Footer Watermark */}
      <View style={styles.footer} fixed>
        <Text>Generated by COGS Automated Engine • Verified A4 PDF Document</Text>
        <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
      </View>
    </Page>
  </Document>
);

// --- 3. POST API ROUTE HANDLER ---
export async function POST(request: Request) {
  try {
    const { fromDate, toDate, ownerTab } = await request.json();

    if (!fromDate || !toDate) {
      return NextResponse.json({ error: 'Date range required' }, { status: 400 });
    }

    const botToken = TELEGRAM_CONFIG.botToken || process.env.TELEGRAM_BOT_TOKEN;
    const chatId = TELEGRAM_CONFIG.chatId || process.env.TELEGRAM_CHAT_ID;

    if (!botToken || !chatId) {
      return NextResponse.json({ error: 'Telegram credentials missing' }, { status: 500 });
    }

    // 🔥 FIXED: Includes Service Role Key fallback to prevent RLS read blocks
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // 🔥 FIXED: Added Cambodia Timezone (+07:00) so Postgres doesn't shift by 7 hours
    const [{ data: sales }, { data: retailSales }] = await Promise.all([
      supabase.from('sales').select('*').gte('created_at', `${fromDate}T00:00:00+07:00`).lte('created_at', `${toDate}T23:59:59+07:00`),
      supabase.from('retail_sales').select('*').gte('created_at', `${fromDate}T00:00:00+07:00`).lte('created_at', `${toDate}T23:59:59+07:00`)
    ]);

    // 🔥 FIXED: Mirrors your Frontend's exact .split('T')[0] matching logic
    const rawSales = [...(sales || []), ...(retailSales || [])].filter((s) => {
      if (!s.created_at) return false;
      const d = s.created_at.split('T')[0];
      const matchesDate = d >= fromDate && d <= toDate;
      const owner = parseOwner(s.owner);
      const matchesOwner = ownerTab === 'mom' ? owner === 'Mom' : owner !== 'Mom';
      return matchesDate && matchesOwner;
    });

    if (rawSales.length === 0) {
      return NextResponse.json({ error: 'No COGS records found for this selection' }, { status: 404 });
    }

    // Clean & calculate row totals
    let grandTotal = 0;
    const cleanRows: any[] = [];

    rawSales.forEach((item) => {
      const desc = item.custom_rice_type || item.rice_type || '';
      const price = Number(item.cogs_price || 0);
      const qty = Number(item.qty || 0);

      if (desc.includes('សេវាដឹក') || (desc.includes('បាវ') && price === 0)) return;

      let amount = Math.abs(qty * price);
      const isNegative = desc.includes('ដូរ') || desc.includes('បញ្ចុះតម្លៃ') || desc.includes('កក់');
      if (isNegative) amount = -amount;

      grandTotal += amount;
      cleanRows.push({ ...item, calculatedAmount: amount, isNegative });
    });

    const tabLabel = ownerTab === 'mom' ? 'Mom COGS' : 'Pich / Jing / Both COGS';

    // Compile JSX to PDF Buffer
    const pdfBuffer = await renderToBuffer(
      <CogsReportDocument
        rows={cleanRows}
        grandTotal={grandTotal}
        fromDate={fromDate}
        toDate={toDate}
        tabLabel={tabLabel}
      />
    );

    // 🔥 FIXED: Wrapped in Uint8Array to satisfy strict TypeScript Blob typing
    const pdfBlob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });

    // Send as PDF attachment via `/sendDocument`
    const tgFormData = new FormData();
    tgFormData.append('chat_id', chatId);
    tgFormData.append('document', pdfBlob, `COGS-${ownerTab.toUpperCase()}-${fromDate}.pdf`);
    tgFormData.append(
      'caption',
      `🌾 <b>${tabLabel} A4 REPORT</b>\n📅 Date: <b>${fromDate} to ${toDate}</b>\n💰 Total Due: <b>${formatRiel(grandTotal)}</b>\n✅ Attached: Multi-page A4 PDF`
    );
    tgFormData.append('parse_mode', 'HTML');

    const tgRes = await fetch(`https://api.telegram.org/bot${botToken}/sendDocument`, {
      method: 'POST',
      body: tgFormData
    });

    const tgResult = await tgRes.json();

    if (!tgRes.ok) {
      throw new Error(`Telegram Upload Error: ${JSON.stringify(tgResult)}`);
    }

    return NextResponse.json({ success: true, messageId: tgResult.result?.message_id });
  } catch (error: any) {
    console.error('Telegram PDF Generate Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}